### ISSUE TITLE
Support query string binding for Option<'T>

### ISSUE THREAD

**Issue by diegobfernandez** [dustinmoris/Giraffe#51]
When binding from a query string to a record with a field of type `int option` this exception happens.
Haven't try with form/json/xml binding.

```
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: TypeConverter cannot convert from System.String.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Giraffe.HttpContextExtensions.HttpContext-BindQueryString@86-1.Invoke(PropertyInfo p)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Giraffe.HttpContextExtensions.HttpContext-BindQueryString@82.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotSupportedException: TypeConverter cannot convert from System.String.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Giraffe.HttpContextExtensions.HttpContext-BindQueryString@86-1.Invoke(PropertyInfo p)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Giraffe.HttpContextExtensions.HttpContext-BindQueryString@82.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)<---
```

**Comment by nojaf** [comment]
This is actually a Json.NET thing, see https://gist.github.com/isaacabraham/ba679f285bfd15d2f53e.
Might be interesting to include these extra converters by default in Giraffe.
@dustinmoris thoughts?

**Comment by diegobfernandez** [comment]
I meant Query String binding :)
This is the model I'm trying to bind to:
``` fsharp
[<CLIMutable>]
type Query =
    { pattern: string
      page: int
      perPage: int
      userId: string
      dataViewId: int option }
```
and the code to do the binding:
``` fsharp
let! query = ctx.BindQueryString<Query>()
```
That line gives me the exception.
I can give it a try and submit a PR if it seems doable.

_I don't currently use JSON payload on my requests, althoug that link provide a lot of insights for future needs, I think for now it should be mentioned on docs and after people feedback may be enabled by default._

**Comment by nojaf** [comment]
Oh, my bad.

**Comment by dustinmoris** [comment]
Hey guys, yes I think we could add a case for options to the binding of the query string.

**Comment by diegobfernandez** [comment]
I'll do a PR for this soon, just finishing the tests.
